### ISSUE TITLE
Need README

### ISSUE THREAD

**Issue by peter279k** [alexdodonov/mezon-pop3-client#1]
As title, it should need README to let developers know how to use.

**Comment by alexdodonov** [comment]
Hi! Thanks for your feedback. I shall provide it soon.

**Comment by alexdodonov** [comment]
The documentation was added. Is it OK now?

**Comment by peter279k** [comment]
@alexdodonov, thanks for your reply to resolve this issue quickly :)!

I also create related PR to improve this initialized `README`.

Once this PR is reviewed and merged, this issue I think will be resolved/closed :).

**Comment by alexdodonov** [comment]
Thanks for your PR )
